services:
  - type: web
    name: quiz-app-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/quiz-app-1.0-SNAPSHOT.jar --spring.profiles.active=render
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://Quizzy:quizzy@cluster0.5nc0uzo.mongodb.net/quizapp?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGODB_DATABASE
        value: quizapp
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: PORT
        value: 8080
      - key: GEMINI_API_KEY
        sync: false
